name: Bug Report
description: If something isn't working as expected.
labels: [ 'type: bug' ]

body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: addon
    attributes:
      label: Addon
      description: What addon are you using?
      options:
        - GBPN
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true

  - type: input
    id: addon-version
    attributes:
      label: Addon version
      description: What version of the addon are you using? Please be as specific as possible.
    validations:
      required: true

  - type: input
    id: gramps-version
    attributes:
      label: Gramps version
      description: What version of Gramps are you using? Please be as specific as possible.
      placeholder: 6.0.0
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: What operating systems are you seeing the problem on?
      multiple: true
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Use this field to provide any other notes that you feel might be relevant to the issue.
