register(
    GRAMPLET,
    id="GBPN",
    name=_("GBPN"),
    description=_("Gramplet interface for Gazetteer of British Placenames (GBPN)."),
    authors=["Owen Voke"],
    authors_email=["development@voke.dev"],
    status=EXPERIMENTAL,
    version="1.0.0",
    gramps_target_version="6.0",
    fname="gbpn.py",
    gramplet="GBPN",
    height=375,
    detached_width=510,
    detached_height=480,
    expand=True,
    gramplet_title=_("GBPN"),
    include_in_listing=True,
)
